// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xx.proto

package go2cache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Dau struct {
	DeviceID             string   `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	ChannelName          string   `protobuf:"bytes,2,opt,name=channelName" json:"channelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dau) Reset()         { *m = Dau{} }
func (m *Dau) String() string { return proto.CompactTextString(m) }
func (*Dau) ProtoMessage()    {}
func (*Dau) Descriptor() ([]byte, []int) {
	return fileDescriptor_xx_d093bf7fe6886dbb, []int{0}
}
func (m *Dau) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dau.Unmarshal(m, b)
}
func (m *Dau) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dau.Marshal(b, m, deterministic)
}
func (dst *Dau) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dau.Merge(dst, src)
}
func (m *Dau) XXX_Size() int {
	return xxx_messageInfo_Dau.Size(m)
}
func (m *Dau) XXX_DiscardUnknown() {
	xxx_messageInfo_Dau.DiscardUnknown(m)
}

var xxx_messageInfo_Dau proto.InternalMessageInfo

func (m *Dau) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *Dau) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func init() {
	proto.RegisterType((*Dau)(nil), "com.dsp.sdk2setting.mq.api.Dau")
}

func init() { proto.RegisterFile("xx.proto", fileDescriptor_xx_d093bf7fe6886dbb) }

var fileDescriptor_xx_d093bf7fe6886dbb = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xa8, 0xa8, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4a, 0xce, 0xcf, 0xd5, 0x4b, 0x29, 0x2e, 0xd0, 0x2b, 0x4e,
	0xc9, 0x36, 0x2a, 0x4e, 0x2d, 0x29, 0xc9, 0xcc, 0x4b, 0xd7, 0xcb, 0x2d, 0xd4, 0x4b, 0x2c, 0xc8,
	0x54, 0x72, 0xe6, 0x62, 0x76, 0x49, 0x2c, 0x15, 0x92, 0xe2, 0xe2, 0x48, 0x49, 0x2d, 0xcb, 0x4c,
	0x4e, 0xf5, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x14, 0xb8, 0xb8,
	0x93, 0x33, 0x12, 0xf3, 0xf2, 0x52, 0x73, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0xd2, 0xc8,
	0x42, 0x4e, 0x4c, 0x01, 0x8c, 0x49, 0x6c, 0x60, 0xbb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0x11, 0x13, 0x25, 0x77, 0x00, 0x00, 0x00,
}
