# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

##


GET http://127.0.0.1:9898/v1/load
###

GET https://10.0.0.193/v1/load
###


##
POST  http://127.0.0.1:9091/v1/load
Content-Type: application/json

{
  "uid": 10,
  "name": "大石头"
}

### bind query
GET  http://127.0.0.1:9091/v1/bindQuery?uid=10&name=大嘻嘻嘻
